filebeat.autodiscover:
  providers:
    - type: docker
      templates:
        - condition:
            contains:
              docker.container.image: studyslot
          config:
            - type: container
              paths:
                - '/var/lib/docker/containers/${data.docker.container.id}/*.log'
              json.keys_under_root: true
              json.overwrite_keys: true
              json.add_error_key: true

processors:
  - add_docker_metadata: ~

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "studyslot-logs-%{+yyyy.MM.dd}"

setup.ilm.enabled: false
setup.template.name: "studyslot-logs"
setup.template.pattern: "studyslot-logs-*"

logging.level: warning